env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - standard-with-typescript
  - prettier
overrides:
  - files:
      - 'src/**/**/*.stories.@(ts|tsx|js)'
    extends:
      - plugin:storybook/recommended
    rules:
      import/no-default-export: off
      import/no-extraneous-dependencies: off
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
plugins:
  - react
  - react-hooks
rules:
  {
    react-hooks/rules-of-hooks: error,
    react-hooks/exhaustive-deps: warn,
    react/react-in-jsx-scope: off,
    semi: off,
    '@typescript-eslint/semi': off,
    '@typescript-eslint/consistent-type-definitions': off,
    'react/no-unknown-property': ['error', { 'ignore': ['css'] }]
  }
